# numpy stuff

###### cool cool cool 

In [43]:
import numpy as np

In [44]:
#returns nd array with number of zeros specified
z5 = np.zeros(5)

In [45]:
z5

array([0., 0., 0., 0., 0.])

In [46]:
# returns number of zeros in the shape specified
z34 = np.zeros((3,4))

In [47]:
z34

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

dimension = axis

n(axis) = rank

shape = tuple containing the axis lengths => rank = length of shape

In [48]:
# get the shape of the ndarray
z34.shape 

(3, 4)

In [49]:
#get the number of dimensions of the array
z34.ndim

2

In [50]:
#get the product of the elements in shape which tells us the number of elements in the ndarray
z34.size

12

In [51]:
#create an n dimensional array
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
# spit the type of the array
type(np.zeros((2,3,4)))

numpy.ndarray

In [53]:
#similar to np.zeros excepp youll have ones inside
o42 = np.ones((4,2))

In [54]:
o42

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
#fills the array with the element specified. here it will be filled with 42 cuz 
f42 = np.full((4,2), 42)

In [56]:
f42

array([[42, 42],
       [42, 42],
       [42, 42],
       [42, 42]])

In [57]:
# np.pi == 3.148369
fpi42 = np.full((4,2), np.pi)

In [58]:
fpi42

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [59]:
# the element which is going to be inside is unpredictable. it is whatever is in the memory at that point.
np.empty((4,2))

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [60]:
# converts virgin python lists to chad ndarray
np.array([[8,3,3,2,9],[8,1,4,9,8]])

array([[8, 3, 3, 2, 9],
       [8, 1, 4, 9, 8]])

In [61]:
#works like python range function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#also works with float values
np.arange(1.0, 4.0)

array([1., 2., 3.])

In [63]:
#can provide steps cuz its similar to range in vanilla python brih
np.arange(1.0, 10.0, 2.0)

array([1., 3., 5., 7., 9.])

In [64]:
#when dealing with float step values, the number of elements varies. might not be what you expected it to be
np.arange(1.0, 10.0, 5/3)

array([1.        , 2.66666667, 4.33333333, 6.        , 7.66666667,
       9.33333333])

In [65]:
#which is why you use linspace. it returns an ndarray with 'step' number of equally spaced elements
np.linspace(1.0, 10.0, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])